apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [../../overlays/dev]
patches:
  - target: {kind: PeerAuthentication, name: mini-commerce-strict}
    patch: |-
      - op: replace
        path: /spec/mtls/mode
        value: PERMISSIVE
