apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [../../base]
patches:
  - target: {kind: ClusterImagePolicy}
    patch: |-
      - op: add
        path: /spec/mode
        value: enforce
