apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets
  namespace: argocd
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/component: addon
    app.kubernetes.io/part-of: exchange-settlement
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/play-builder/argocd-gitops.git
        revision: main
        files:
          - path: "argocd/appsets/envs/*.json"
  template:
    metadata:
      name: "external-secrets-{{ .env }}"
      namespace: argocd
      labels:
        app.kubernetes.io/name: external-secrets
        app.kubernetes.io/component: addon
        app.kubernetes.io/part-of: exchange-settlement
        environment: "{{ .env }}"
      annotations:
        argocd.argoproj.io/sync-wave: "1"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: "{{ .project }}"
      source:
        repoURL: https://charts.external-secrets.io
        chart: external-secrets
        targetRevision: "{{ .esoVersion }}"
        helm:
          releaseName: external-secrets
          values: |
            installCRDs: true
            serviceAccount:
              create: true
              name: external-secrets
              annotations:
                eks.amazonaws.com/role-arn: "{{ .esoIrsaRoleArn }}"
            webhook:
              create: {{ .esoWebhook }}
            certController:
              create: {{ .esoCertController }}
      destination:
        server: https://kubernetes.default.svc
        namespace: external-secrets
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
        retry:
          limit: "{{ .retryLimit }}"
          backoff:
            duration: "{{ .retryDuration }}"
            factor: 2
            maxDuration: "{{ .retryMaxDuration }}"
