apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-sa
  annotations:
    # IRSA role for app pod AWS access
    eks.amazonaws.com/role-arn: "arn:aws:iam::346135039532:role/exchange-settlement-dev-app"
