apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: exchange-settlement-dev
  namespace: argocd
  labels:
    app.kubernetes.io/name: exchange-settlement
    environment: dev
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: exchange-settlement
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: exchange-settlement-dev
  source:
    repoURL: https://github.com/play-builder/argocd-gitops.git
    targetRevision: main
    path: kustomize/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: app-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 3m
