apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: exchange-settlement-prod
  namespace: argocd
  labels:
    app.kubernetes.io/name: exchange-settlement
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: exchange-settlement
    environment: prod
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/play-builder/argocd-gitops.git
    targetRevision: main
    path: kustomize/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: app-prod
  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
