{{- include "sample-app.validateKind" . -}}
{{- if eq .Values.workload.kind "Deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sample-app.fullname" . }}
  namespace: {{ include "sample-app.namespace" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    {{- include "sample-app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.deployment.maxSurge }}
      maxUnavailable: {{ .Values.deployment.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "sample-app.selectorLabels" . | nindent 6 }}
  template:
    {{- include "sample-app.podTemplate" . | nindent 4 }}
{{- else }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "sample-app.fullname" . }}
  namespace: {{ include "sample-app.namespace" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    {{- include "sample-app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  revisionHistoryLimit: 3
  {{- if gt (int .Values.rollout.rollbackWindow.revisions) 0 }}
  rollbackWindow:
    revisions: {{ .Values.rollout.rollbackWindow.revisions }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sample-app.selectorLabels" . | nindent 6 }}
  strategy:
    canary:
      stableService: {{ include "sample-app.fullname" . }}-stable
      canaryService: {{ include "sample-app.fullname" . }}-canary
      trafficRouting:
        plugins:
          argoproj-labs/gatewayAPI:
            httpRoute: {{ include "sample-app.fullname" . }}
            namespace: {{ include "sample-app.namespace" . }}
      steps:
        {{- toYaml .Values.rollout.canary.steps | nindent 8 }}
  template:
    {{- include "sample-app.podTemplate" . | nindent 4 }}
{{- end }}
