{{- if .Values.database.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mini-commerce.databaseFullname" . }}
  namespace: {{ include "mini-commerce.namespace" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: mini-commerce
    app.kubernetes.io/component: database
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: postgresql
      port: {{ .Values.database.port }}
      targetPort: postgresql
      protocol: TCP
{{- end }}
