apiVersion: v1
kind: Service
metadata:
  name: {{ include "mini-commerce.fullname" . }}-stable
  namespace: {{ include "mini-commerce.namespace" . }}
  labels:
    {{- include "mini-commerce.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "mini-commerce.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: public
      protocol: TCP
{{- if eq .Values.workload.kind "Rollout" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mini-commerce.fullname" . }}-canary
  namespace: {{ include "mini-commerce.namespace" . }}
  labels:
    {{- include "mini-commerce.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "mini-commerce.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: public
      protocol: TCP
{{- end }}
