{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ include "mini-commerce.namespace" . }}
  labels:
    {{- include "mini-commerce.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
