{{- include "mini-commerce.validateKind" . -}}
{{- if eq .Values.workload.kind "Deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mini-commerce.fullname" . }}
  namespace: {{ include "mini-commerce.namespace" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    {{- if .Values.externalSecrets.enabled }}
    secret.reloader.stakater.com/reload: {{ include "mini-commerce.runtimeSecretName" . | quote }}
    {{- end }}
  labels:
    {{- include "mini-commerce.labels" . | nindent 4 }}
spec:
  {{- if .Values.maintenance.writersStopped }}
  replicas: 0
  {{- else if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.workload.revisionHistoryLimit }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.deployment.maxSurge }}
      maxUnavailable: {{ .Values.deployment.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "mini-commerce.selectorLabels" . | nindent 6 }}
  template:
    {{- include "mini-commerce.podTemplate" . | nindent 4 }}
{{- else }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "mini-commerce.fullname" . }}
  namespace: {{ include "mini-commerce.namespace" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    {{- if .Values.externalSecrets.enabled }}
    secret.reloader.stakater.com/reload: {{ include "mini-commerce.runtimeSecretName" . | quote }}
    reloader.stakater.com/rollout-strategy: rollout
    {{- end }}
  labels:
    {{- include "mini-commerce.labels" . | nindent 4 }}
spec:
  {{- if .Values.maintenance.writersStopped }}
  replicas: 0
  {{- else if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.workload.revisionHistoryLimit }}
  {{- if gt (int .Values.rollout.rollbackWindow.revisions) 0 }}
  rollbackWindow:
    revisions: {{ .Values.rollout.rollbackWindow.revisions }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mini-commerce.selectorLabels" . | nindent 6 }}
  strategy:
    canary:
      stableService: {{ include "mini-commerce.fullname" . }}-stable
      canaryService: {{ include "mini-commerce.fullname" . }}-canary
      trafficRouting:
        plugins:
          argoproj-labs/gatewayAPI:
            httpRoute: {{ include "mini-commerce.fullname" . }}
            namespace: {{ include "mini-commerce.namespace" . }}
      steps:
        {{- toYaml .Values.rollout.canary.steps | nindent 8 }}
  template:
    {{- include "mini-commerce.podTemplate" . | nindent 4 }}
{{- end }}
