database:
  enabled: true
  replicaCount: 0
  migration:
    enabled: false
maintenance:
  writersStopped: true
snapshot:
  captureEnabled: true
recovery:
  restoreEnabled: false
  namespace: app-recovery
  snapshotClassName: course-ebs-snapshots
  source:
    namespace: app-dev
    pvcName: data-sample-app-postgresql-0
    snapshotName: sample-app-postgresql-snapshot
