environment: dev

namespace:
  name: app-dev
  labels:
    gateway-access: "true"
    environment: dev

image:
  repository: "REPLACE_ME_ACCOUNT_ID.dkr.ecr.REPLACE_ME_REGION.amazonaws.com/REPLACE_ME_PROJECT/sample-app"
  digest: "sha256:0000000000000000000000000000000000000000000000000000000000000000"

database:
  enabled: false
  migrationImage:
    repository: "REPLACE_ME_ACCOUNT_ID.dkr.ecr.REPLACE_ME_REGION.amazonaws.com/REPLACE_ME_PROJECT/sample-app"
    digest: "sha256:0000000000000000000000000000000000000000000000000000000000000000"

workload:
  kind: Deployment

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70

podDisruptionBudget:
  enabled: false

externalSecrets:
  enabled: true
  awsRegion: "REPLACE_ME_REGION"
  readerRoleArn: "arn:aws:iam::REPLACE_ME_ACCOUNT_ID:role/dev-REPLACE_ME_PROJECT-external-secrets-reader-role"
  remoteSecretName: "sample-app/dev/app-secrets"

gateway:
  enabled: true
  hostname: "sample-app.dev.example.com"
  httpEnabled: true
  httpsEnabled: false

rollout:
  analysis:
    enabled: false
