apiVersion: v1
kind: ResourceQuota
metadata:
  name: mini-commerce
  namespace: app-dev
  annotations: {argocd.argoproj.io/sync-wave: "-10"}
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 12Gi
    limits.cpu: "24"
    limits.memory: 24Gi
    pods: "30"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: mini-commerce
  namespace: app-dev
  annotations: {argocd.argoproj.io/sync-wave: "-10"}
spec:
  limits:
    - type: Container
      defaultRequest: {cpu: 100m, memory: 128Mi}
      default: {cpu: 500m, memory: 256Mi}
