# ClusterSecretStore - Cluster-wide AWS Secrets Manager reference
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secrets
  labels:
    app.kubernetes.io/name: app
    app.kubernetes.io/managed-by: kustomize
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
