# ExternalSecret - Syncs secrets from AWS Secrets Manager
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-secrets
  labels:
    app.kubernetes.io/name: app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: app-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_NAME
      remoteRef:
        key: OVERRIDE_IN_OVERLAY
        property: DB_NAME
    - secretKey: DB_USER
      remoteRef:
        key: OVERRIDE_IN_OVERLAY
        property: DB_USER
    - secretKey: DB_HOST
      remoteRef:
        key: OVERRIDE_IN_OVERLAY
        property: DB_HOST
    - secretKey: DB_PORT
      remoteRef:
        key: OVERRIDE_IN_OVERLAY
        property: DB_PORT
    - secretKey: DB_PASSWORD
      remoteRef:
        key: OVERRIDE_IN_OVERLAY
        property: DB_PASSWORD
    - secretKey: API_KEY
      remoteRef:
        key: OVERRIDE_IN_OVERLAY
        property: API_KEY
    - secretKey: API_SECRET
      remoteRef:
        key: OVERRIDE_IN_OVERLAY
        property: API_SECRET
    - secretKey: JWT_SECRET
      remoteRef:
        key: OVERRIDE_IN_OVERLAY
        property: JWT_SECRET
    - secretKey: ENCRYPTION_KEY
      remoteRef:
        key: OVERRIDE_IN_OVERLAY
        property: ENCRYPTION_KEY
