# Namespace - Logical isolation boundary
apiVersion: v1
kind: Namespace
metadata:
  name: app
  labels:
    app.kubernetes.io/name: app
    app.kubernetes.io/environment: dev
    pod-security.kubernetes.io/enforce: restricted
