# ServiceAccount - Identity for pod processes
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-sa
  labels:
    app.kubernetes.io/name: app
    app.kubernetes.io/component: serviceaccount
    app.kubernetes.io/part-of: exchange-settlement
    app.kubernetes.io/managed-by: kustomize
automountServiceAccountToken: false
