apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../bootstrap/prod

patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: ApplicationSet
      name: mini-commerce-prod
    patch: |-
      - op: add
        path: /spec/template/spec/syncPolicy/managedNamespaceMetadata/labels/pod-security.kubernetes.io~1enforce
        value: restricted
      - op: add
        path: /spec/template/spec/syncPolicy/managedNamespaceMetadata/labels/pod-security.kubernetes.io~1enforce-version
        value: "{{ .podSecurityVersion }}"
  - target:
      group: admissionregistration.k8s.io
      version: v1
      kind: ValidatingAdmissionPolicyBinding
      name: course-workload-security
    patch: |-
      - op: replace
        path: /spec/validationActions
        value:
          - Deny
