apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../bootstrap/prod

patches:
  - target:
      version: v1
      kind: Namespace
      name: app-prod
    patch: |-
      - op: add
        path: /metadata/labels/pod-security.kubernetes.io~1enforce
        value: restricted
      - op: add
        path: /metadata/labels/pod-security.kubernetes.io~1enforce-version
        value: v1.36
  - target:
      group: admissionregistration.k8s.io
      version: v1
      kind: ValidatingAdmissionPolicyBinding
      name: course-workload-security
    patch: |-
      - op: replace
        path: /spec/validationActions
        value:
          - Deny
